package com.utils;

public enum FakePeerType {
    VALID,
    CLOSE_IN_FIRST_REQUEST,
    RESPOND_WITH_DELAY_100,
    RESPOND_WITH_DELAY_3000,
    SEND_LESS_DATA_THEN_REQUESTED,
    VALID_AND_SEND_CHOKE_AFTER_2_REQUESTS
}
