package com.utils;

public enum PeerMessageType {
    HANDSHAKE,
    BIT_FIELD_MESSAGE,
    CANCEL_MESSAGE,
    CHOKE_MESSAGE,
    HAVE_MESSAGE,
    INTERESTED_MESSAGE,
    IS_ALIVE_MESSAGE,
    NOT_INTERESTED_MESSAGE,
    PIECE_MESSAGE,
    REQUEST_MESSAGE,
    UNCHOKE_MESSAGE
}
