package main.torrent.status;

public enum Action {
    INITIALIZE,

    START_DOWNLOAD_IN_PROGRESS,
    START_DOWNLOAD_WIND_UP,

    PAUSE_DOWNLOAD_IN_PROGRESS,
    PAUSE_DOWNLOAD_WIND_UP,

    RESUME_DOWNLOAD_IN_PROGRESS,
    RESUME_DOWNLOAD_WIND_UP,

    START_UPLOAD_IN_PROGRESS,
    START_UPLOAD_WIND_UP,

    PAUSE_UPLOAD_IN_PROGRESS,
    PAUSE_UPLOAD_WIND_UP,

    RESUME_UPLOAD_IN_PROGRESS,
    RESUME_UPLOAD_WIND_UP,

    COMPLETED_DOWNLOADING_IN_PROGRESS,
    COMPLETED_DOWNLOADING_WIND_UP,

    REMOVE_TORRENT_IN_PROGRESS,
    REMOVE_TORRENT_WIND_UP,

    REMOVE_FILES_IN_PROGRESS,
    REMOVE_FILES_WIND_UP,

    START_LISTENING_TO_INCOMING_PEERS_IN_PROGRESS,
    START_LISTENING_TO_INCOMING_PEERS_WIND_UP,

    PAUSE_LISTENING_TO_INCOMING_PEERS_IN_PROGRESS,
    PAUSE_LISTENING_TO_INCOMING_PEERS_WIND_UP,

    RESUME_LISTENING_TO_INCOMING_PEERS_IN_PROGRESS,
    RESUME_LISTENING_TO_INCOMING_PEERS_WIND_UP,

    START_SEARCHING_PEERS_IN_PROGRESS,
    START_SEARCHING_PEERS_WIND_UP,

    PAUSE_SEARCHING_PEERS_IN_PROGRESS,
    PAUSE_SEARCHING_PEERS_WIND_UP,

    RESUME_SEARCHING_PEERS_IN_PROGRESS,
    RESUME_SEARCHING_PEERS_WIND_UP
}

