package main.torrent.status;

public enum StatusType {
    START_DOWNLOAD,
    START_UPLOAD,
    PAUSE_DOWNLOAD,
    RESUME_DOWNLOAD,
    PAUSE_UPLOAD,
    RESUME_UPLOAD,
    COMPLETED_DOWNLOADING,
    REMOVE_TORRENT,
    REMOVE_FILES,
    START_LISTENING_TO_INCOMING_PEERS,
    RESUME_LISTENING_TO_INCOMING_PEERS,
    PAUSE_LISTENING_TO_INCOMING_PEERS,
    START_SEARCHING_PEERS,
    RESUME_SEARCHING_PEERS,
    PAUSE_SEARCHING_PEERS
}
