package main.torrent.status;

public enum TorrentStatusType {
    START_DOWNLOAD,
    NOT_START_DOWNLOAD,
    START_UPLOAD,
    NOT_START_UPLOAD,
    PAUSE_DOWNLOAD,
    RESUME_DOWNLOAD,
    PAUSE_UPLOAD,
    RESUME_UPLOAD,
    COMPLETED_DOWNLOADING,
    NOT_COMPLETED_DOWNLOADING,
    REMOVE_TORRENT,
    NOT_REMOVE_TORRENT,
    REMOVE_FILES,
    NOT_REMOVE_FILES,
    START_LISTENING_TO_INCOMING_PEERS,
    NOT_START_LISTENING_TO_INCOMING_PEERS,
    RESUME_LISTENING_TO_INCOMING_PEERS,
    PAUSE_LISTENING_TO_INCOMING_PEERS,
    START_SEARCHING_PEERS,
    NOT_START_SEARCHING_PEERS,
    RESUME_SEARCHING_PEERS,
    PAUSE_SEARCHING_PEERS
}
